## Configuration parameters for the teb method
## Read the guidance at the bottom of this file before use.

## Star name
star_name: BEBOP-3  # Data must be in file <star_name>.yaml
run_id: run01   # Prefix used in output save file

## Flux ratio priors
# List of bands to include in flux ratio priors
# Comment out this section if your do not want to apply priors
# on the flux ratio. See notes below for bands available.
flux_ratio_priors:
# - NUV
 - BP
 - J
 - H
 - Ks
 - W1
 - W2
 - W3
# Color - Teff tabulations to use for flux ratio priors
color_table1: auto
color_table2: auto

# Model SED - uncomment one option
model_sed: bt-settl           # Model SEDs to use 
#model_sed: bt-settl-cifist    # Model SEDs to use 
#model_sed: coelho-sed         # Model SEDs to use 
binning:  50                  # Model SED resolution, Angstrom

# Extinction model
# See synphot.reddening.ReddeningLaw
extinction_model: mwavg

## SED distortion  
# Set n_coeffs=0 to disable use of distortion functions
n_coeffs: 6         # Number of distortion coefficients to use.

# Priors on external noise values for each data type
# The error on the measurement x_i with quoted standard error e_i is assumed
# to have a true standard error sqrt(e_i**2 + sigma_x**2), were sigma_x
# applies to all the observations of the same type ("sigma_m" for magnitudes,
# "sigma_r" for flux ratios, etc.).
#
# The hyper-parameters sigma_x are assumed to have an exponential prior 
# P(sigma_x) = { exp(-sigma_x/sigma_x_prior)/sigma_x_prior   sigma_x >= 0  
#              { 0                                           sigma_x < 0 
# If the prior is set to a large value then it will have little impact on the
# results.
#
sigma_m_prior: 0.1         # magnitude data
sigma_r_prior: 0.005       # flux ratios
sigma_c_prior: 0.1         # colors

# MCMC and display options
mcmc_n_burnin: 1024      # Number of burn-in steps for emcee
mcmc_n_sample:  512       # Number of output steps for emcee
mcmc_n_walkers: 256       # Number of emcee walkers
mcmc_n_thin: 4             # Thinning factor for output chains
mcmc_show_progress: True  # Show emcee progress meter display - True or False

### HOW TO USE THIS CONFIGURATION FILE

## A note on flux ratio priors
# Priors on the flux ratio at UV / NIR wavelengths are applied
# based on the computed flux ratio in the Gaia RP band and the 
# two effective temperatures using tabulated color - Teff
# relations. The following tables of color - Teff relations
# are currently available:
# galah:
#   log_g > 3.5, 3800 - 9000 K,
#   FUV, NUV, BP, J, H, Ks, W1, W2, W3
#
# mdwarf:
#   M-dwarfs, 3700 - 4300 K,
#   FUV, NUV, BP, J, H, Ks, W1, W2, W3
#
# If "auto" is selected then "galah" is used if teff1 > 4000,
# otherise "mdwarf" is used, and same for teff2.
# 

## A note on the model SEDs
# BT-Settl, BT-Settl-CIFIST and to a lesser extent, Coelho SED models
# are supported by teb
#
# teb will interpolate to the specified values of Teff, logg and [M/H] 
#
# N.B. not all T_eff-log(g) combinations are supported by all model
# catalogs.
#
# BT-Settl:
#  Asplund et al. (2009) solar abundances.
#  M/H = [0.5, 0.3, # 0.0, -0.5, -1.0, ..., -4.0]
#  http://svo2.cab.inta-csic.es/theory/newov2/index.php?models=bt-settl
#
# BT-Settl-CIFIST:
#   Caffau et al. (2011) solar abundances.
#   [M/H] =  0.
# http://svo2.cab.inta-csic.es/theory/newov2/index.php?models=bt-settl-cifist
#   N.B. teb will overwrite [M/H] if != 0.
# 
# Coelho SED:
#  Limited range 130nm - 10um, sparse teff-logg
#  M/H = # [0.2, 0.0, -0.1, -0.3, -0.5, -0.8, -1.0, -1.3]
#  http://svo2.cab.inta-csic.es/theory/newov2/index.php?models=coelho_sed
#  Using these SEDs may give spurious results due to the limited
#  wavelength range
