## Read the guidance at the bottom of this file before use.
#

## Model parameters for reference SED
teff1: 6462                   # T_eff,1 [K]
teff2: 6331                   # T_eff,2 [K]
logg1: 3.9836                 # log(g) for star 1 [cgs]
logg2: 4.3297                 # log(g) for star 2 [cgs]
m_h:   0.0                    # [M/H] for both stars.
aFe:   0.0                    # [alpha/Fe] for both stars.

# Parallax 
parallax:     # parallax and error, in mas
  - 2.6311
  - 0.0197

## Stellar radii - all in nominal solar units.
# Use EITHER secondary_radius: OR radius_ratio 
primary_radius:    # Primary star radius and error
  - 1.9288
  - 0.0030
secondary_radius: # Secondary star radius and error
  - 1.1815
  - 1.1815

## Reddening
# Prior on interstellar E(B-V) - value and error
# Comment out or delete this section to not use a prior
# From Maxted 2025 using EW NaI D1 = 0.0074 ± 0.0006
ebv:
  - 0.004
  - 0.013    # Maxted 2025

# Measured flux ratios
flux_ratios:
  - tag: TESS
    band: TESS/TESS.Red
    value:         # Value and standard error
      - 0.3517
      - 0.0009

  - tag: B
    band: Generic.Johnson.B
    value:
      - 0.3299
      - 0.0012

  - tag: V
    band: Generic.Johnson.V
    value:
      - 0.3413
      - 0.0008

  - tag: R
    band: Generic.Johnson.R
    value:
      - 0.3475
      - 0.0009

  - tag: I
    band: Generic.Johnson.I
    value:
      - 0.3517
      - 0.0008

# Photometry
magnitudes:
  - tag: G
    band: GAIA/GAIA3.G
    mag:           # Value and standard error 
      - 10.3431
      - 0.0028

  - tag: Gbp
    band: GAIA/GAIA3.Gbp
    mag:           # Value and standard error 
      - 10.5757
      - 0.0029

  - tag: Grp
    band: GAIA/GAIA3.Grp
    mag:           # Value and standard error 
      - 9.9575
      - 0.0038

  - tag: J
    band: 2MASS/2MASS.J
    mag:           # Value and standard error 
      - +9.554
      - 0.027
  - tag: H
    band: 2MASS/2MASS.H
    mag:           # Value and standard error 
      - +9.380
      - 0.026
  - tag: Ks
    band: 2MASS/2MASS.Ks
    mag:           # Value and standard error 
      - +9.283
      - 0.023

  - tag: NUV
    band: GALEX/GALEX.NUV
    mag:           # Value and standard error 
      - +14.187
      - 0.009

  - tag: u
    band: SkyMapper/SkyMapper.u
    mag:           # Value and standard error 
      - +11.734
      - 0.012

  - tag: v
    band: SkyMapper/SkyMapper.v
    mag:           # Value and standard error 
      - +11.292
      - 0.014

  - tag: W1
    band: WISE/WISE.W1
    mag:           # Value and standard error 
      - +9.238
      - 0.023

  - tag: W2
    band: WISE/WISE.W2
    mag:           # Value and standard error 
      - +9.257
      - 0.020

  - tag: W3
    band: WISE/WISE.W3
    mag:           # Value and standard error 
      - +9.233
      - 0.027


# Photometric colors
#colors:
#  - tag: b-y
#    type: by
#    color:         # Value and standard error
#      - 
#      - 

### HOW TO USE THIS CONFIGURATION FILE
#
## Parallax
#  With zero-point correction for Gaia, if needed.
#
## A note on the stellar radii
# If you have very precise measurements for radii (0.2% or better),
# these should be the Rosseland radii. See Miller & Maxted, 
# 2020MNRAS.497.2899M 
#
## Flux ratios
# tag (str): Unique name for measurement, can be same as band
# band (str): Bandpass name from SVO filter profile service.
# value (float): Flux ratio value. Must be greater than 0.
# error (float): Error in flux ratio.

## Magnitudes
# tag (str): Unique name for measurement, can be same as band
# band (str): Bandpass name from SVO filter profile service.
# mag (float): Value and error for the magnitude
#
# Data on the zero-point, etc. for each band must be listed in
#  config/database.csv. See calspec.py for instructions on generating
#  these data.
#
## colors
# tag (str): Unique name for measurement, can be same as color ID
# type (str): Color name. Only Strömgren b-y (by), m1 (m1), c1 (c1)
# color (float): color value and error.
