## Read the guidance at the bottom of this file before use.
#

## Model parameters for reference SED
teff1: 6156                   # T_eff,1 [K]
teff2: 3350                   # T_eff,2 [K]
logg1: 4.15                   # log(g) for star 1 [cgs]
logg2: 5.00                   # log(g) for star 2 [cgs]
m_h:   -0.3                   # [M/H] for both stars.
aFe:    0.0                   # [alpha/Fe] for both stars.

# Parallax 
parallax:     # parallax and error, in mas
  - 5.6616
  - 0.0338

## Stellar radii - all in nominal solar units.
# Use EITHER secondary_radius: OR radius_ratio 
primary_radius:    # Primary star radius and error
  - 1.417
  - 0.014
#radius_ratio:      # Secondary radius / primary radius and error
#  - 
#  - 
secondary_radius:  # Secondary star radius and error
  - 0.215
  - 0.002

## Reddening
# Prior on interstellar E(B-V) - value and error
# Comment out or delete this section to not use a prior
ebv:
  - 0.004
  - 0.013

# Measured flux ratios
flux_ratios:
  - tag: TESS
    band: TESS/TESS.Red
    value:         # Value and standard error
      - 0.00155
      - 0.00008

  - tag: CHEOPS
    band: CHEOPS/CHEOPS.band
    value:         # Value and standard error
      - 0.00088
      - 0.00005

# Photometry
magnitudes:
  - tag: G
    band: GAIA/GAIA3.G
    mag:           # Value and standard error 
      - 9.9205
      - 0.0028

  - tag: Gbp
    band: GAIA/GAIA3.Gbp
    mag:           # Value and standard error 
      - 10.1967
      - 0.0028

  - tag: Grp
    band: GAIA/GAIA3.Grp
    mag:           # Value and standard error 
      - 9.4772
      - 0.0038

  - tag: J
    band: 2MASS/2MASS.J
    mag:           # Value and standard error 
      - +8.982
      - 0.024
  - tag: H
    band: 2MASS/2MASS.H
    mag:           # Value and standard error 
      - +8.692
      - 0.029
  - tag: Ks
    band: 2MASS/2MASS.Ks
    mag:           # Value and standard error 
      - +8.620
      - 0.024

  - tag: NUV
    band: GALEX/GALEX.NUV
    mag:           # Value and standard error 
      - 14.28
      - 0.71

  - tag: gP1
    band: PAN-STARRS/PS1.g
    mag:           # Value and standard error 
      - 10.249
      -  0.020

  - tag: rP1
    band: PAN-STARRS/PS1.r
    mag:           # Value and standard error 
      - 9.961
      - 0.024

  - tag: iP1
    band: PAN-STARRS/PS1.i
    mag:           # Value and standard error 
      - 9.868
      - 0.021

  - tag: W1
    band: WISE/WISE.W1
    mag:           # Value and standard error 
      - +8.604
      - 0.023

  - tag: W2
    band: WISE/WISE.W2
    mag:           # Value and standard error 
      - +8.632
      - 0.020

  - tag: W3
    band: WISE/WISE.W3
    mag:           # Value and standard error 
      - +8.619
      - 0.025


# Photometric colors
#colors:
#  - tag: b-y
#    type: by
#    color:         # Value and standard error
#      - 
#      - 

### HOW TO USE THIS CONFIGURATION FILE
#
## Parallax
#  With zero-point correction for Gaia, if needed.
#
## A note on the stellar radii
# If you have very precise measurements for radii (0.2% or better),
# these should be the Rosseland radii. See Miller & Maxted, 
# 2020MNRAS.497.2899M 
#
## Flux ratios
# tag (str): Unique name for measurement, can be same as band
# band (str): Bandpass name from SVO filter profile service.
# value (float): Flux ratio value. Must be greater than 0.
# error (float): Error in flux ratio.

## Magnitudes
# tag (str): Unique name for measurement, can be same as band
# band (str): Bandpass name from SVO filter profile service.
# mag (float): Value and error for the magnitude
#
# Data on the zero-point, etc. for each band must be listed in
#  config/database.csv. See calspec.py for instructions on generating
#  these data.
#
## colors
# tag (str): Unique name for measurement, can be same as color ID
# type (str): Color name. Only Strömgren b-y (by), m1 (m1), c1 (c1)
# color (float): color value and error.
